### ISSUE TITLE
pie chart It can be?

### ISSUE THREAD

**Issue by pheromone** [capitalone/react-native-pathjs-charts#145] opened 2017-05-03 10:03 UTC
![default](https://cloud.githubusercontent.com/assets/14305431/25656264/c8a9a1ee-302a-11e7-915e-e4ec09c7660f.png)

**Comment by marzolfb** [comment] 2017-05-03 13:36
I believe this is a duplicate of #105. I would welcome a pull request from anyone that wants to work on a pie chart legend.

**Closed by marzolfb** 2017-05-03 13:36 UTC
Labels: duplicate
