### ISSUE TITLE
Floats improperly handled in axis scaling / points calculation

### ISSUE THREAD

**Issue by Cody-G-G** [capitalone/react-native-pathjs-charts#84] opened 2017-02-14 02:51 UTC
My dataset has the following X values: 1.78, 1.83, 2.0, 2.46.

![16731731_1255859791150820_448227196_o](https://cloud.githubusercontent.com/assets/9220445/22912911/d60ee410-f25f-11e6-8be2-7e87ed89d418.png)

As you can see, it gets quite ugly...some (simple?) solutions would be to limit the number of digits after the decimal point (I imagine 2 digits for the fractional part would be sufficient for scenarios that involve mobile graphs....), or rounding the fractional part after a number of digits over the decimal point.

Edit: I see this is an issue from the lodash range method...maybe since lodash is MIT licensed the method can simply be copied and improved with the proper handling?

**Comment by marzolfb** [comment] 2017-02-14 14:12
This is likely a duplicate of #28 - but will need to take a closer look later.

**Comment by marzolfb** [comment] 2017-02-17 14:31
@Cody-G-G See my design thoughts on #28 - you have any feedback to contribute there?

**Closed** 2017-02-17 14:32 UTC
Labels: duplicate
