### ISSUE TITLE
No chart visible

### ISSUE THREAD

**Issue by jotamontecino** [capitalone/react-native-pathjs-charts#10] opened 2016-10-13 15:12 UTC
I added one of your chart exemple, and i have an empty view. I added a text before to be sure it wasn't render outside of the visible field.... 
<img width="366" alt="capture d ecran 2016-10-13 a 17 08 48" src="https://cloud.githubusercontent.com/assets/16019281/19354717/0275fdd0-9168-11e6-895d-01acc4aa8d66.png">

It should be rendered in the StockLine.

Am i doing something wrong?

**Comment by Ansalibrahim** [comment] 2016-10-16 09:15
for me, my simulator does not show, however in my android device it works as intended

**Comment by jotamontecino** [comment] 2016-10-17 07:12
I'll try on my devices

**Comment by tinygipxy** [comment] 2016-10-17 16:29
me too, seem iOS 10 bug

**Comment by dfconroy** [comment] 2016-10-18 23:43
Any way to get the charts to display on the simulator?

**Comment by Ansalibrahim** [comment] 2016-10-19 02:35
I think it may be related to svg support in iOS simulator so I don't think that it could be cleared. I tried a lot but no chance around.
Don't consider it is a serious since it is still visible in real device so it is only a matter of time for a developer. I've also similar issues in react native libraries that uses react native svg so that is something related to the svg support in safari in the simulator

**Comment by drpiou** [comment] 2016-10-19 13:19
Me too, nothing is displayed on my iOS 9 and 10 devices. I have the exact same screenshot as OP.

**Comment by marzolfb** [comment] 2016-10-24 23:31
Interesting. I'm not seeing the same thing after upgrading to xCode8(/iOS10). I suspect there is something else going in a parent component above the StockLineChart. I'm curious what you see if you simplify things by taking the example app and removing everything but the StockLineChart. 

Here's what I have in index.ios.js

```
class example extends React.Component {
  render() {
    return (
      <ScrollView style={{flex:1,backgroundColor:'#F5FCFF'}} contentContainerStyle={{justifyContent:'center',alignItems:'center'}}>
        <StockLine data={sampleData.stockLine.data} options={sampleData.stockLine.options} xKey='x' yKey='y' />
      </ScrollView>)
  }
}
```

and what it produced for me in the simulator:

![image](https://cloud.githubusercontent.com/assets/1242149/19667702/445b9e74-9a07-11e6-9cc1-c0f2cdad9bba.png)


what happens when you do the same?

**Comment by marzolfb** [comment] 2016-11-03 20:40
Closing this issue as I haven't seen anyone provide any more info to reproduce the issue. We recently upgraded the project to use React Native 0.35. Not sure that clears up some of the problems above, but it may be worth a try to get the latest to see if it fixes previous problems.

**Closed by marzolfb** 2016-11-03 20:40 UTC

**Comment by SimchaShats** [comment] 2016-11-10 18:58
Have the same issue on RN 0.37 on real device and emulator also... But it worked good before upgrade on previous RN 0.32
