### ISSUE TITLE
Error while updating property 'd' in shadow node of type : RNSVGPath

### ISSUE THREAD

**Issue by vinhhrv** [capitalone/react-native-pathjs-charts#118] opened 2017-03-19 16:46 UTC
I copied code from your sample, but when i run, i got this error

Error while updating property 'd' in shadow node of type : RNSVGPath

`
let data = [
      [{
        "v": 49,
        "name": "apple"
      }, {
        "v": 42,
        "name": "apple"
      }],
      [{
        "v": 69,
        "name": "banana"
      }, {
        "v": 62,
        "name": "banana"
      }],
      [{
        "v": 29,
        "name": "grape"
      }, {
        "v": 15,
        "name": "grape"
      }]
    ]`
`let options = {
      width: 300,
      height: 300,
      margin: {
        top: 20,
        left: 25,
        bottom: 50,
        right: 20
      },
      color: '#2980B9',
      gutter: 20,
      animate: {
        type: 'oneByOne',
        duration: 200,
        fillTransition: 3
      },
      axisX: {
        showAxis: true,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: false,
        orient: 'bottom',
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: true,
          fill: '#34495E'
        }
      },
      axisY: {
        showAxis: true,
        showLines: true,
        showLabels: true,
        showTicks: true,
        zeroAxis: false,
        orient: 'left',
        label: {
          fontFamily: 'Arial',
          fontSize: 8,
          fontWeight: true,
          fill: '#34495E'
        }
     }`
    }`

`<Bar data={data} options={options} accessorKey='v'/>`

**Comment by paneer-tikka** [comment] 2017-03-20 08:27
I faced the same issue. Upon debugging on Android, realized that I needed to update react-native-svg to latest version with the followign change in package.json:
`"react-native-svg": "~5.1.5"`
[Forked here](https://github.com/paneer-tikka/react-native-pathjs-charts) and now working fine.

**Comment by marzolfb** [comment] 2017-03-21 06:13
This is a duplicate of several other issues - have a look at #70 and see if some of that discussion helps. 

Manually upgrading to react-native-svg 5.1.5 as @paneer-tikka suggests could solve your problem but we haven't upgrading to a newer version of this dependency in this library due to a text rotation bug in react-native-svg in that newer version - this bug is evident if you look at the Bar chart in the example app.

Likely, there is a conflict between your app's copy of react-native-svg and this libraries insistence on wanting version 4.5.0 of that dependency. It should become evident that this is the case if you take a look at the output of this command:

```
 npm list react-native react-native-svg paths-js
```

**Comment by paneer-tikka** [comment] 2017-03-21 06:28
Thanks @marzolfb. I was wondering what's going to hit me after the upgrade ;-). Luckily I am able to work around the Bar char issue for now.

**Comment by marzolfb** [comment] 2017-03-26 16:47
Closing this since its a duplicate

**Closed by marzolfb** 2017-03-26 16:47 UTC
Labels: duplicate
