### ISSUE TITLE
How do you set the min for axisY for stockline chart?

### ISSUE THREAD

**Issue by joeylu** [capitalone/react-native-pathjs-charts#104] opened 2017-03-08 05:59 UTC
I'm using the stockline chart example, seems the axisY min value always starts with the lowest value of the object array (which is 40579 in the example), is there anyway to set it to 0? or any specific number?

**Comment by joeylu** [comment] 2017-03-08 06:05
nevermind, putting min/max in option solves the problem, tks

**Comment by joeylu** [comment] 2017-03-08 06:10
Another question :)
is there anyway to set the custom steps for the axisY? for example, with min: 0, max: 100, the steps are set to 20 on axisY automatically, how can I set it to 50? tks

**Comment by marzolfb** [comment] 2017-03-08 06:24
Take a look at the discussion on #97 - specifically regarding the `tickCount` option. This issue is very similar to your question. I just reopened #97 because @pahmed has stated that the `tickCount` option isn't working entirely as expected.

**Comment by marzolfb** [comment] 2017-03-08 06:34
@joeylu If you agree your question is a duplicate of #97, I can close this one and we can track further discussion on that issue. Does #97 address your question above?

**Comment by joeylu** [comment] 2017-03-09 03:54
@marzolfb yes, please close this one, I will keep tracking the #97 , tks so much, great chart library for react!

**Closed** 2017-03-10 13:09 UTC
