### ISSUE TITLE
Colors for multiple lines

### ISSUE THREAD

**Issue by evantahler** [capitalone/react-native-pathjs-charts#100] opened 2017-03-02 00:55 UTC
Hi! 

Thank you for this library.

Right now, it looks like `color` is only a HEX string or some object with a `.color` property, which is a string.  It would be great to be able to specify an array of colors to correspond to each data array being passed in.

Currently, it looks like the color is modified "magically" in [`cyclic`](https://github.com/capitalone/react-native-pathjs-charts/blob/master/src/Line.js#L62) for each subsequent data array.

<img width="356" alt="screen shot 2017-03-01 at 4 55 35 pm" src="https://cloud.githubusercontent.com/assets/303226/23488190/e7ea5c54-fe9f-11e6-8f12-2fe2b7f49b73.png">

---

Before filing an issue please ensure the following boxes are checked, if applicable:

- [X] I have searched for existing issues
- [X] I have provided detailed instructions that can reproduce the issue (including code and data necessary)

**Comment by evantahler** [comment] 2017-03-02 01:09
The palate options as described here doesn't seem to work for line charts https://github.com/capitalone/react-native-pathjs-charts/pull/22

**Comment by marzolfb** [comment] 2017-03-02 07:13
Duplicate of #51 - see [my comments there](https://github.com/capitalone/react-native-pathjs-charts/issues/51#issuecomment-274288474)

**Closed by marzolfb** 2017-03-02 07:13 UTC
