### ISSUE TITLE
Chart is not getting drawn at the center of the view

### ISSUE THREAD

**Issue by sachin-sable** [capitalone/react-native-pathjs-charts#8] opened 2016-10-06 10:44 UTC
Pie chart is always drawn with it's center as parent view's top left corner. How to give the center point as Parent View's center?

**Comment by sachin-sable** [comment] 2016-10-07 09:09
<img width="223" alt="2016-10-07_1439" src="https://cloud.githubusercontent.com/assets/3263453/19184664/dc3aaff6-8c9b-11e6-91eb-9ec51e107db4.png">

**Comment by shalini3001** [comment] 2016-10-12 17:22
I have exactly the same issue. It looks like it happens only with Pie chart.

**Comment by Ansalibrahim** [comment] 2016-10-19 02:44
have you tried "justify-content:centre" and "align-items:centre" in your chart style.

Since it is not a General issue I would strongly suggest you to post the code including the styles of the parent layout and the chart layout

**Comment by marzolfb** [comment] 2016-10-24 22:23
@sachin-sable @shalini3001 Could one of you provide some sample data/code that helps show how to reproduce the result? I tried tweaking the example app so that it only showed the pie chart and I couldn't get the same behavior as stated above. I even removed the `style` and `contentContainerStyle` attributes from the parent `ScrollView` and I didn't get the same behavior when running on the iOS simulator. Here's the reduced snippet from the `index.ios.js` file from the example app:
```
class example extends React.Component {
  render() {
    return (
      <ScrollView>
       <Pie
          data={sampleData.pie.data}
          options={sampleData.pie.options}
          accessorKey="population" />
      </ScrollView>)
  }
}
```
and it comes out looking like this:

![image](https://cloud.githubusercontent.com/assets/1242149/19666131/7aa4a5a2-99fd-11e6-91c8-253b7c980248.png)

**Comment by Jarda8** [comment] 2016-10-29 14:21
I have the same issue too. The code and the data are taken from the example project (src in attachment).
`return (
          <ScrollView style={{flex:1,backgroundColor:'#F5FCFF'}}
                  contentContainerStyle={{justifyContent:'center',alignItems:'center'}}>
            <Pie
              data={data}
              options={options}
              accessorKey="population" />
          </ScrollView>
        );`
The result is the same without styling. I am running it with Exponent on Genymotion Android emulator (Google Nexus 5X - 6.0.0 - API 23).
[ExpensesPiechart.js.txt](https://github.com/capitalone/react-native-pathjs-charts/files/559963/ExpensesPiechart.js.txt)

**Comment by marzolfb** [comment] 2016-11-04 16:55
@Jarda8 Thanks for the example code/data. I tried running your example with the most recent merged changes that upgraded this project to React Native 0.35 with your identical setup (Exponent+Genymotion+same device you have above), and I didn't see the behavior of the pie chart showing up in the top left corner - I saw it correctly rendered in the center like so:

![image](https://cloud.githubusercontent.com/assets/1242149/20014520/91e3324a-a274-11e6-97c7-17274140cf59.png)

So maybe the upgrade to React Native 0.35 addressed this issue? Could you give the latest changes a try and see if that fixes it for you?

**Comment by SimchaShats** [comment] 2016-11-09 08:27
I had the same bug, to Fix it need to add property "center: [100, 100]" or other coordinates to options opfpie...

**Comment by marzolfb** [comment] 2016-11-10 19:34
@SimchaShats Could you put the "pie graph doesn't render with only 1 data item" bug you mentioned above into a separate issue?

I think the "adding custom colors" feature you mentioned above, is covered by #5 (Thanks for the helpful feedback on that one). 

Given all this, once we have a new issue for the pie graph with 1 data item bug, I will close this one out.

**Comment by SimchaShats** [comment] 2016-11-10 19:38
Ok

**Closed** 2016-11-10 21:04 UTC
Labels: bug
